# ---------- Stage 1: Build ----------
FROM docker.io/library/node:24-slim AS build
WORKDIR /app

# Copy dependency manifests and install
COPY package.json package-lock.json ./
RUN npm install

# Copy only required project files
COPY src ./src
COPY public ./public
COPY index.html ./
COPY tsconfig.json ./
COPY tsconfig.app.json ./
COPY tsconfig.node.json ./
COPY vite.config.ts ./
COPY eslint.config.js ./

ENV TSC_COMPILE_ON_ERROR=true
RUN npm run build

# ---------- Stage 2: Nginx ----------
FROM docker.io/library/nginx:trixie-perl 
# FROM docker.io/library/debian:trixie-slim
# RUN apt-get update && apt-get install -y --no-install-recommends \
    # nginx \
    # && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/share/nginx/html

# Remove default nginx static files
RUN rm -rf ./*

# Copy built frontend from previous stage
COPY --from=build /app/dist ./

# Copy nginx config
COPY container/nginx.conf /etc/nginx/conf.d/default.conf

COPY container/docker-entrypoint.sh container/docker-entrypoint.sh

EXPOSE 80
CMD ["bash","container/docker-entrypoint.sh"]

